config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "application#index"

  post "loans/pay/:id", to: "loans#pay", as: 'pay_loan'

  resources :loans do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  validates :value, presence: true
  validates :paytime, presence: true

  belongs_to :user

  def pay
    self.paid = true
    save
  end

  def to(user)
    self.user_id = user.id unless user.unpaid_loans?
  end

  def paid_text
    paid ? "Pago!" : "Aberto"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :loans

  def unpaid_loans?
    !loans.where("paid = ?", false).empty?
  end

  def ordered_loans
    loans.sort_by(&:created_at).reverse!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :mocks_user, only: [:index, :create]

  protect_from_forgery with: :exception

  def index
    render "layouts/application"
  end

  private

  def mocks_user
    @current_user = User.first
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:pay]

  def create
    @loan = Loan.new loan_params
    @loan.to(@current_user)

    if @loan.save
      redirect_to root_path,
                  notice: "Emprestimo processado. Verifique sua situação na aba 'Sua situação'"
    else
      redirect_to root_path,
                  alert: "Emprestimo não aceito! Você deve pagar seu último empréstimo"
    end
  end

  def pay
    @loan.pay
    UserMailer.send_verification_mail
    redirect_to root_path
  end

  private

  def loan_params
    params.require(:loan).permit(:value, :paytime)
  end

  def set_loan
    @loan = Loan.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/layouts/_infos.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_main_navbar.html.erb
<ul class="nav nav-tabs">
<li class="active"><a aria-expanded="true" href="#loan" data-toggle="tab">Empréstimo</a> </li>
<li class=""><a aria-expanded="false" href="#situation" data-toggle="tab">Sua situação</a> </li>
</ul>
<div id="myTabContent" class="tab-content">
  <%= render "loans/loan_panel" %>
  <%= render "loans/loans_situation" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agiot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <%= render 'layouts/infos' %>

  <body>
    <%= render 'layouts/main_navbar' %>
  </body>

</html>

app/views/loans/_loan_panel.html.erb
<div class="tab-pane fade active in" id="loan">
  <div class="loan-form center">
    <div class="panel panel-warning">
      <div class="panel-heading">
        Quanto você quer emprestado?
      </div>
      <div class="panel-body">
        <%= form_for :loan, url: loans_path, html: { class: 'form-horizontal form-group' } do |f| %>
          <div class="form-group">
            <%= f.label :value, value: 'Valor', class: 'control-label margin-1em' %>
            <%= f.number_field :value, class: 'form-control center input' %>
          </div>
          <div class="form-group">
            <%= f.label :paytime, value: 'Meses para pagar', 
              class: 'control-label margin-1em'%>
            <%= f.number_field :paytime, class: 'form-control center input' %>
          </div>
          <%= f.submit "Pedir!", class: "btn btn-warning btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/loans/_loan_situation.html.erb
<tr>
  <td><%= loan.value  %></td>
  <td><%= loan.paid_text  %></td>
  <td>
    <% if !loan.paid %>
      <%= button_to "Pagar!", pay_loan_path(loan.id),
        class: 'btn btn-success btn-sm' %>
    <% end %>
  </td>
</tr>

app/views/loans/_loans_situation.html.erb
<div class="tab-pane fade" id="situation">
<div class="loan-form center">
  <div class="panel panel-warning">
    <div class="panel-heading">
      Seus empréstimos
    </div>
    <div class="panel-body">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Valor pego</th>
            <th>Situação</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'loans/loan_situation', 
            collection: @current_user.ordered_loans,
            as: :loan %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>